export enum JobError {
    VALIDATION_FAILED = 'VALIDATION_FAILED',
    PROFANITY_DETECTED = 'PROFANITY_DETECTED',
    GENERATION_TIMEOUT = 'GENERATION_TIMEOUT',
    AI_SERVICE_ERROR = 'AI_SERVICE_ERROR',
    SUPABASE_UPLOAD_ERROR = 'SUPABASE_UPLOAD_ERROR',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
} 