
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from './types';

const supabaseUrl = 'https://nphkufnrodsvvyxyaglc.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5waGt1Zm5yb2RzdnZ5eHlhZ2xjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2MzE1MDksImV4cCI6MjA1MTIwNzUwOX0.9ggX3t0ImzZ1Ep2p5ePw7lDoe5M0uDa3vvVNM-HvGR0';

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Supabase URL and Anon Key must be provided in environment variables.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);
